# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 110, 271, 401))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 511, 401))
        self.label_2.setStyleSheet("border-radius:20px;\n"
"border-image: url(:/icons/image/会议.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(680, 100, 101, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(0, 255, 255);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/最小化 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 72, 61))
        self.label_4.setStyleSheet("border-image: url(:/icons/image/常用信息.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"color: rgb(85, 170, 127);")
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(510, 160, 261, 351))
        self.frame_2.setMinimumSize(QtCore.QSize(261, 351))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 261, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 261, 261))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_R_name_2 = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_R_name_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_name_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_R_name_2.setObjectName("lineEdit_R_name_2")
        self.verticalLayout_2.addWidget(self.lineEdit_R_name_2)
        self.lineEdit_L_account = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_L_account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_account.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_L_account.setObjectName("lineEdit_L_account")
        self.verticalLayout_2.addWidget(self.lineEdit_L_account)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_password.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.verticalLayout_2.addWidget(self.lineEdit_L_password)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_login)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setStyleSheet("QPushButton{\n"
"background-color: rgb(33, 165, 4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_2.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2.addWidget(self.page_login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_R_name = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_name.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_name.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_R_name.setObjectName("lineEdit_R_name")
        self.verticalLayout_3.addWidget(self.lineEdit_R_name)
        self.lineEdit_R_account_2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_account_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_account_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_R_account_2.setObjectName("lineEdit_R_account_2")
        self.verticalLayout_3.addWidget(self.lineEdit_R_account_2)
        self.lineEdit_password_1 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_password_1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_password_1.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_1.setObjectName("lineEdit_password_1")
        self.verticalLayout_3.addWidget(self.lineEdit_password_1)
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_password_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_password_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.verticalLayout_3.addWidget(self.lineEdit_password_2)
        self.lineEdit_R_email = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_email.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_email.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_R_email.setObjectName("lineEdit_R_email")
        self.verticalLayout_3.addWidget(self.lineEdit_R_email)
        self.pushButton_R_sure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_R_sure.setStyleSheet("QPushButton{\n"
"background-color: rgb(33, 165, 4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_3.addWidget(self.pushButton_R_sure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_L_account_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_L_account_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_account_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_L_account_2.setObjectName("lineEdit_L_account_2")
        self.verticalLayout_6.addWidget(self.lineEdit_L_account_2)
        self.lineEdit_L_password_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_L_password_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_password_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_L_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password_2.setObjectName("lineEdit_L_password_2")
        self.verticalLayout_6.addWidget(self.lineEdit_L_password_2)
        self.pushButton_L_sure_2 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_L_sure_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(33, 165, 4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_L_sure_2.setObjectName("pushButton_L_sure_2")
        self.verticalLayout_6.addWidget(self.pushButton_L_sure_2)
        self.stackedWidget_2.addWidget(self.page_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(-1, 260, 261, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/管理员登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_Register.setStyleSheet("QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_Register.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/用户注册 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon3)
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout_2.addWidget(self.pushButton_Register)
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_Login.setStyleSheet("QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_Login.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icon/用户登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon4)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout_2.addWidget(self.pushButton_Login)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 261, 51))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_8 = QtWidgets.QLabel(self.page_6)
        self.label_8.setGeometry(QtCore.QRect(90, 20, 201, 21))
        self.label_8.setStyleSheet("\n"
"font: 10pt \"幼圆\";\n"
"color: rgb(43, 130, 64);")
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_6)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.page_5.setObjectName("page_5")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 131, 29))
        self.label_9.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"幼圆\";")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setStyleSheet("font: 10pt \"幼圆\";\n"
"color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"幼圆\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(40, 0, 221, 61))
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"幼圆\";")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_10 = QtWidgets.QLabel(self.page_7)
        self.label_10.setGeometry(QtCore.QRect(60, 10, 180, 29))
        self.label_10.setStyleSheet("font: 10pt \"幼圆\";\n"
"color: rgb(255, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Machine learning systems"))
        self.lineEdit_R_name_2.setPlaceholderText(_translate("MainWindow", "用户名："))
        self.lineEdit_L_account.setPlaceholderText(_translate("MainWindow", "账号:"))
        self.lineEdit_L_password.setPlaceholderText(_translate("MainWindow", "密码："))
        self.pushButton_L_sure.setText(_translate("MainWindow", "确认"))
        self.lineEdit_R_name.setPlaceholderText(_translate("MainWindow", "用户名："))
        self.lineEdit_R_account_2.setPlaceholderText(_translate("MainWindow", "账号："))
        self.lineEdit_password_1.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_password_2.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.lineEdit_R_email.setPlaceholderText(_translate("MainWindow", "邮箱："))
        self.pushButton_R_sure.setText(_translate("MainWindow", "注册"))
        self.lineEdit_L_account_2.setPlaceholderText(_translate("MainWindow", "管理员账号:"))
        self.lineEdit_L_password_2.setPlaceholderText(_translate("MainWindow", "管理员密码："))
        self.pushButton_L_sure_2.setText(_translate("MainWindow", "确认"))
        self.label_8.setText(_translate("MainWindow", "WELCOME!"))
        self.label_9.setText(_translate("MainWindow", "注册成功!"))
        self.label_3.setText(_translate("MainWindow", "账号或密码不能为空！"))
        self.label_6.setText(_translate("MainWindow", "密码错误或账号不存在"))
        self.label_7.setText(_translate("MainWindow", "两次密码输入不一致！"))
        self.label_10.setText(_translate("MainWindow", "用户名已经存在！"))
import res_rc
