# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.resize(964, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 761, 561))
        self.frame.setMinimumSize(QtCore.QSize(761, 561))
        self.frame.setStyleSheet("border-top-left-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-top-left-radius:20px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("font: 12pt \"幼圆\";\n"
"border:none;\n"
"padding-bottom:5px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/机器学习.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_2.addWidget(self.pushButton_logout)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/最小化 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    background-color: rgb(84, 124, 62);\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"background-color: rgb(84, 124, 62);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"background-color: rgb(84, 124, 62);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border_bottom-right-radius:20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 571, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(0, 0, 571, 491))
        self.label.setStyleSheet("border-image: url(:/images/image/阅读.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page_home)
        self.label_3.setGeometry(QtCore.QRect(180, 440, 271, 31))
        self.label_3.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(40, 121, 59);")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_home)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_7 = QtWidgets.QFrame(self.page_3)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 571, 91))
        self.frame_7.setStyleSheet("#frame_4{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_fetch_users = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_fetch_users.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_fetch_users.setObjectName("pushButton_fetch_users")
        self.horizontalLayout_4.addWidget(self.pushButton_fetch_users)
        self.pushButton_search_user = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_search_user.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_search_user.setObjectName("pushButton_search_user")
        self.horizontalLayout_4.addWidget(self.pushButton_search_user)
        self.pushButton_add_user = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_add_user.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_add_user.setObjectName("pushButton_add_user")
        self.horizontalLayout_4.addWidget(self.pushButton_add_user)
        self.pushButton_delete_user = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_delete_user.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_delete_user.setObjectName("pushButton_delete_user")
        self.horizontalLayout_4.addWidget(self.pushButton_delete_user)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 80, 551, 421))
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.tableWidget = QtWidgets.QTableWidget(self.page_8)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 561, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setStyleSheet("")
        self.page_9.setObjectName("page_9")
        self.lineEdit_searchName = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_searchName.setGeometry(QtCore.QRect(140, 80, 239, 35))
        self.lineEdit_searchName.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_searchName.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_searchName.setObjectName("lineEdit_searchName")
        self.label_2 = QtWidgets.QLabel(self.page_9)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 301, 41))
        self.label_2.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_search = QtWidgets.QPushButton(self.page_9)
        self.pushButton_search.setGeometry(QtCore.QRect(390, 70, 71, 40))
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_search.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_search.setObjectName("pushButton_search")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_9)
        self.tableWidget_4.setGeometry(QtCore.QRect(5, 140, 571, 192))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.page_9)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 72, 71))
        self.label_5.setStyleSheet("border-image: url(:/images/image/GULULU-自由神.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.stackedWidget_2.addWidget(self.page_9)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_7 = QtWidgets.QLabel(self.page_6)
        self.label_7.setGeometry(QtCore.QRect(140, 10, 301, 41))
        self.label_7.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.lineEdit_updateName = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_updateName.setGeometry(QtCore.QRect(160, 60, 239, 35))
        self.lineEdit_updateName.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateName.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateName.setObjectName("lineEdit_updateName")
        self.label_8 = QtWidgets.QLabel(self.page_6)
        self.label_8.setGeometry(QtCore.QRect(120, 110, 381, 41))
        self.label_8.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.lineEdit_updateAccount = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_updateAccount.setGeometry(QtCore.QRect(160, 160, 239, 35))
        self.lineEdit_updateAccount.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateAccount.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateAccount.setObjectName("lineEdit_updateAccount")
        self.lineEdit_updatePassword = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_updatePassword.setGeometry(QtCore.QRect(160, 210, 239, 35))
        self.lineEdit_updatePassword.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updatePassword.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updatePassword.setObjectName("lineEdit_updatePassword")
        self.pushButton_update = QtWidgets.QPushButton(self.page_6)
        self.pushButton_update.setGeometry(QtCore.QRect(220, 320, 71, 40))
        self.pushButton_update.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_update.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_update.setObjectName("pushButton_update")
        self.lineEdit_update_email = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_update_email.setGeometry(QtCore.QRect(160, 260, 239, 35))
        self.lineEdit_update_email.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_update_email.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_update_email.setObjectName("lineEdit_update_email")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setGeometry(QtCore.QRect(30, 20, 72, 71))
        self.label_14.setStyleSheet("border-image: url(:/images/image/GULULU-自由神.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 301, 41))
        self.label_9.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.lineEdit_delete_name = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_delete_name.setGeometry(QtCore.QRect(150, 80, 239, 35))
        self.lineEdit_delete_name.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_delete_name.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_delete_name.setObjectName("lineEdit_delete_name")
        self.pushButton_delete = QtWidgets.QPushButton(self.page_7)
        self.pushButton_delete.setGeometry(QtCore.QRect(220, 140, 71, 40))
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_delete.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label_15 = QtWidgets.QLabel(self.page_7)
        self.label_15.setGeometry(QtCore.QRect(40, 30, 72, 71))
        self.label_15.setStyleSheet("border-image: url(:/images/image/GULULU-自由神.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_7)
        self.label_16.setGeometry(QtCore.QRect(10, 200, 561, 211))
        self.label_16.setStyleSheet("border-image: url(:/images/image/夏天.png);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.stackedWidget_2.addWidget(self.page_7)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setGeometry(QtCore.QRect(10, 0, 571, 91))
        self.frame_8.setStyleSheet("#frame_4{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_view_all_experiments = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_view_all_experiments.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_view_all_experiments.setObjectName("pushButton_view_all_experiments")
        self.horizontalLayout_5.addWidget(self.pushButton_view_all_experiments)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_8.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_delete_experiment_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_delete_experiment_2.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_delete_experiment_2.setObjectName("pushButton_delete_experiment_2")
        self.horizontalLayout_5.addWidget(self.pushButton_delete_experiment_2)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_3.setGeometry(QtCore.QRect(10, 100, 561, 401))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_10)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 561, 401))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.stackedWidget_3.addWidget(self.page_10)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.label_4 = QtWidgets.QLabel(self.page_12)
        self.label_4.setGeometry(QtCore.QRect(140, 20, 301, 41))
        self.label_4.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_searchExperimentID = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_searchExperimentID.setGeometry(QtCore.QRect(150, 90, 239, 35))
        self.lineEdit_searchExperimentID.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_searchExperimentID.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_searchExperimentID.setObjectName("lineEdit_searchExperimentID")
        self.pushButton_search_experiment = QtWidgets.QPushButton(self.page_12)
        self.pushButton_search_experiment.setGeometry(QtCore.QRect(220, 150, 71, 40))
        self.pushButton_search_experiment.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_search_experiment.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_search_experiment.setObjectName("pushButton_search_experiment")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_12)
        self.tableWidget_2.setGeometry(QtCore.QRect(-20, 200, 571, 201))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_19 = QtWidgets.QLabel(self.page_12)
        self.label_19.setGeometry(QtCore.QRect(30, 10, 81, 71))
        self.label_19.setStyleSheet("border-image: url(:/images/image/GULULU-彩球罐.png);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.stackedWidget_3.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.label_10 = QtWidgets.QLabel(self.page_13)
        self.label_10.setGeometry(QtCore.QRect(140, 10, 301, 41))
        self.label_10.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.lineEdit_updateName_2 = QtWidgets.QLineEdit(self.page_13)
        self.lineEdit_updateName_2.setGeometry(QtCore.QRect(140, 50, 239, 35))
        self.lineEdit_updateName_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateName_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateName_2.setObjectName("lineEdit_updateName_2")
        self.label_11 = QtWidgets.QLabel(self.page_13)
        self.label_11.setGeometry(QtCore.QRect(140, 100, 291, 41))
        self.label_11.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.lineEdit_updateName_4 = QtWidgets.QLineEdit(self.page_13)
        self.lineEdit_updateName_4.setGeometry(QtCore.QRect(150, 160, 239, 35))
        self.lineEdit_updateName_4.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateName_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateName_4.setObjectName("lineEdit_updateName_4")
        self.lineEdit_updateName_5 = QtWidgets.QLineEdit(self.page_13)
        self.lineEdit_updateName_5.setGeometry(QtCore.QRect(150, 220, 239, 35))
        self.lineEdit_updateName_5.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateName_5.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateName_5.setObjectName("lineEdit_updateName_5")
        self.lineEdit_updateName_6 = QtWidgets.QLineEdit(self.page_13)
        self.lineEdit_updateName_6.setGeometry(QtCore.QRect(150, 270, 239, 35))
        self.lineEdit_updateName_6.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_updateName_6.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_updateName_6.setObjectName("lineEdit_updateName_6")
        self.pushButton_update_2 = QtWidgets.QPushButton(self.page_13)
        self.pushButton_update_2.setGeometry(QtCore.QRect(210, 330, 71, 40))
        self.pushButton_update_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_update_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_update_2.setObjectName("pushButton_update_2")
        self.label_18 = QtWidgets.QLabel(self.page_13)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 81, 71))
        self.label_18.setStyleSheet("border-image: url(:/images/image/GULULU-彩球罐.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.stackedWidget_3.addWidget(self.page_13)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_12 = QtWidgets.QLabel(self.page_11)
        self.label_12.setGeometry(QtCore.QRect(130, 0, 301, 41))
        self.label_12.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit_delete_name_2 = QtWidgets.QLineEdit(self.page_11)
        self.lineEdit_delete_name_2.setGeometry(QtCore.QRect(140, 60, 239, 35))
        self.lineEdit_delete_name_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_delete_name_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_delete_name_2.setObjectName("lineEdit_delete_name_2")
        self.pushButton_delete_2 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_delete_2.setGeometry(QtCore.QRect(210, 120, 71, 40))
        self.pushButton_delete_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_delete_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_delete_2.setObjectName("pushButton_delete_2")
        self.label_17 = QtWidgets.QLabel(self.page_11)
        self.label_17.setGeometry(QtCore.QRect(20, 10, 81, 71))
        self.label_17.setStyleSheet("border-image: url(:/images/image/GULULU-彩球罐.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.page_11)
        self.label_20.setGeometry(QtCore.QRect(-10, 160, 571, 291))
        self.label_20.setStyleSheet("border-image: url(:/images/image/日落.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.stackedWidget_3.addWidget(self.page_11)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_save_admin_info = QtWidgets.QPushButton(self.page_4)
        self.pushButton_save_admin_info.setGeometry(QtCore.QRect(240, 320, 71, 40))
        self.pushButton_save_admin_info.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_save_admin_info.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_save_admin_info.setObjectName("pushButton_save_admin_info")
        self.lineEdit_admin_password = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_admin_password.setGeometry(QtCore.QRect(170, 200, 239, 35))
        self.lineEdit_admin_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_admin_password.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_admin_password.setObjectName("lineEdit_admin_password")
        self.lineEdit_admin_account = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_admin_account.setGeometry(QtCore.QRect(170, 120, 239, 35))
        self.lineEdit_admin_account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_admin_account.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_admin_account.setObjectName("lineEdit_admin_account")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(150, 40, 301, 41))
        self.label_13.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_21 = QtWidgets.QLabel(self.page_4)
        self.label_21.setGeometry(QtCore.QRect(20, 90, 141, 281))
        self.label_21.setStyleSheet("border-image: url(:/images/image/黑锦鲤-竖.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_4)
        self.label_22.setGeometry(QtCore.QRect(320, 300, 231, 191))
        self.label_22.setStyleSheet("border-image: url(:/images/image/黑锦鲤-横.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(240, 210, 72, 15))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow1.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow1)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(3)
        self.stackedWidget_3.setCurrentIndex(3)
        self.pushButton_3.clicked.connect(MainWindow1.close) # type: ignore
        self.pushButton_4.clicked.connect(MainWindow1.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow1", "Machine learning"))
        self.pushButton_7.setText(_translate("MainWindow1", "主页"))
        self.pushButton_2.setText(_translate("MainWindow1", "用户数据管理"))
        self.pushButton_5.setText(_translate("MainWindow1", "实验数据管理"))
        self.pushButton_6.setText(_translate("MainWindow1", "我的"))
        self.label_3.setText(_translate("MainWindow1", "欢迎使用管理员系统"))
        self.pushButton_fetch_users.setText(_translate("MainWindow1", "查看用户信息"))
        self.pushButton_search_user.setText(_translate("MainWindow1", "查找用户信息"))
        self.pushButton_add_user.setText(_translate("MainWindow1", "修改用户信息"))
        self.pushButton_delete_user.setText(_translate("MainWindow1", "删除用户信息"))
        self.lineEdit_searchName.setPlaceholderText(_translate("MainWindow1", "用户名："))
        self.label_2.setText(_translate("MainWindow1", "请输入您想查找的用户名称"))
        self.pushButton_search.setText(_translate("MainWindow1", "搜索"))
        self.label_7.setText(_translate("MainWindow1", "请输入您想修改的用户名称"))
        self.lineEdit_updateName.setPlaceholderText(_translate("MainWindow1", "用户名："))
        self.label_8.setText(_translate("MainWindow1", "请输入您修改的账号,密码和邮箱"))
        self.lineEdit_updateAccount.setPlaceholderText(_translate("MainWindow1", "账号："))
        self.lineEdit_updatePassword.setPlaceholderText(_translate("MainWindow1", "密码："))
        self.pushButton_update.setText(_translate("MainWindow1", "更新"))
        self.lineEdit_update_email.setPlaceholderText(_translate("MainWindow1", "邮箱："))
        self.label_9.setText(_translate("MainWindow1", "请输入您想删除的用户名称"))
        self.lineEdit_delete_name.setPlaceholderText(_translate("MainWindow1", "用户名："))
        self.pushButton_delete.setText(_translate("MainWindow1", "删除"))
        self.pushButton_view_all_experiments.setText(_translate("MainWindow1", "查看实验信息"))
        self.pushButton_8.setText(_translate("MainWindow1", "查找实验数据"))
        self.pushButton_9.setText(_translate("MainWindow1", "修改实验信息"))
        self.pushButton_delete_experiment_2.setText(_translate("MainWindow1", "删除实验信息"))
        self.label_4.setText(_translate("MainWindow1", "请输入您想查找的实验ID"))
        self.lineEdit_searchExperimentID.setPlaceholderText(_translate("MainWindow1", "实验ID："))
        self.pushButton_search_experiment.setText(_translate("MainWindow1", "搜索"))
        self.label_10.setText(_translate("MainWindow1", "请输入您想修改的实验ID"))
        self.lineEdit_updateName_2.setPlaceholderText(_translate("MainWindow1", "实验ID："))
        self.label_11.setText(_translate("MainWindow1", "请输入您修改的实验数据"))
        self.lineEdit_updateName_4.setPlaceholderText(_translate("MainWindow1", "Name："))
        self.lineEdit_updateName_5.setPlaceholderText(_translate("MainWindow1", "Accuracy："))
        self.lineEdit_updateName_6.setPlaceholderText(_translate("MainWindow1", "Loss_rate："))
        self.pushButton_update_2.setText(_translate("MainWindow1", "更新"))
        self.label_12.setText(_translate("MainWindow1", "请输入您想删除的实验ID"))
        self.lineEdit_delete_name_2.setPlaceholderText(_translate("MainWindow1", "实验ID："))
        self.pushButton_delete_2.setText(_translate("MainWindow1", "删除"))
        self.pushButton_save_admin_info.setText(_translate("MainWindow1", "保存"))
        self.lineEdit_admin_password.setPlaceholderText(_translate("MainWindow1", "密码："))
        self.lineEdit_admin_account.setPlaceholderText(_translate("MainWindow1", "账号："))
        self.label_13.setText(_translate("MainWindow1", "请输入您想修改的账号密码"))
        self.label_6.setText(_translate("MainWindow1", "我的"))
import res_rc
