# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 682)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 761, 561))
        self.frame.setMinimumSize(QtCore.QSize(761, 561))
        self.frame.setStyleSheet("border-top-left-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-top-left-radius:20px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("font: 12pt \"幼圆\";\n"
"border:none;\n"
"padding-bottom:5px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/机器学习.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_2.addWidget(self.pushButton_logout)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/最小化 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    background-color: rgb(84, 124, 62);\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"background-color: rgb(84, 124, 62);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"background-color: rgb(84, 124, 62);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setStyleSheet("font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setStyleSheet("font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setStyleSheet("font: 12pt \"幼圆\";\n"
"background-color: rgb(84, 124, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border_bottom-right-radius:20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 571, 501))
        self.stackedWidget.setStyleSheet("border-bottom-right-radius:20px")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(10, 10, 551, 481))
        self.label.setStyleSheet("border-image: url(:/images/image/学习.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.page_home)
        self.label_7.setGeometry(QtCore.QRect(170, 450, 251, 31))
        self.label_7.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(40, 121, 59);")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_home)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(180, 10, 301, 41))
        self.label_9.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.pushButton_select_data = QtWidgets.QPushButton(self.page_3)
        self.pushButton_select_data.setGeometry(QtCore.QRect(210, 410, 121, 40))
        self.pushButton_select_data.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_select_data.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_select_data.setObjectName("pushButton_select_data")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(320, 50, 181, 181))
        self.label_2.setStyleSheet("border-image: url(:/images/image/俯冲鸟-黑.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(70, 250, 161, 131))
        self.label_16.setStyleSheet("border-image: url(:/images/image/仰冲鸟 (1).png);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_select_model_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_select_model_2.setGeometry(QtCore.QRect(0, 80, 91, 40))
        self.pushButton_select_model_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_select_model_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_select_model_2.setObjectName("pushButton_select_model_2")
        self.pushButton_choose_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_choose_3.setGeometry(QtCore.QRect(0, 240, 91, 40))
        self.pushButton_choose_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_choose_3.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_choose_3.setObjectName("pushButton_choose_3")
        self.pushButton_start = QtWidgets.QPushButton(self.page)
        self.pushButton_start.setGeometry(QtCore.QRect(0, 320, 91, 40))
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(110, 0, 421, 271))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);")
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(110, 290, 421, 191))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.pushButton_select_model_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_select_model_3.setGeometry(QtCore.QRect(0, 160, 91, 40))
        self.pushButton_select_model_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_select_model_3.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_select_model_3.setObjectName("pushButton_select_model_3")
        self.pushButton_start_1 = QtWidgets.QPushButton(self.page)
        self.pushButton_start_1.setGeometry(QtCore.QRect(0, 400, 91, 40))
        self.pushButton_start_1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_start_1.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_start_1.setObjectName("pushButton_start_1")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 72, 71))
        self.label_17.setStyleSheet("border-image: url(:/images/image/GULULU-彩虹宝宝.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tableWidget = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget.setGeometry(QtCore.QRect(-5, 21, 561, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(120, 50, 371, 41))
        self.label_15.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_15.setObjectName("label_15")
        self.lineEdit_user_password = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_user_password.setGeometry(QtCore.QRect(150, 190, 239, 35))
        self.lineEdit_user_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_user_password.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_user_password.setObjectName("lineEdit_user_password")
        self.lineEdit_user_email = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_user_email.setGeometry(QtCore.QRect(150, 260, 239, 35))
        self.lineEdit_user_email.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_user_email.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_user_email.setObjectName("lineEdit_user_email")
        self.pushButton_save_user_info = QtWidgets.QPushButton(self.page_5)
        self.pushButton_save_user_info.setGeometry(QtCore.QRect(240, 350, 71, 40))
        self.pushButton_save_user_info.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_save_user_info.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_save_user_info.setObjectName("pushButton_save_user_info")
        self.lineEdit_user_account_2 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_user_account_2.setGeometry(QtCore.QRect(150, 130, 239, 35))
        self.lineEdit_user_account_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_user_account_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_user_account_2.setObjectName("lineEdit_user_account_2")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(0, 90, 141, 251))
        self.label_5.setStyleSheet("border-image: url(:/images/image/仙人掌多肉植物盆栽5.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(390, 90, 141, 251))
        self.label_6.setStyleSheet("border-image: url(:/images/image/仙人掌多肉植物盆栽5.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 571, 91))
        self.frame_7.setStyleSheet("#frame_4{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_model_1 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_model_1.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_model_1.setObjectName("pushButton_model_1")
        self.horizontalLayout_4.addWidget(self.pushButton_model_1)
        self.pushButton_model_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_model_2.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_model_2.setObjectName("pushButton_model_2")
        self.horizontalLayout_4.addWidget(self.pushButton_model_2)
        self.pushButton_model_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_model_3.setStyleSheet("font: 10pt \"幼圆\";\n"
"color:rgb(84, 124, 62);\n"
"")
        self.pushButton_model_3.setObjectName("pushButton_model_3")
        self.horizontalLayout_4.addWidget(self.pushButton_model_3)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 80, 581, 401))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(210, 20, 301, 41))
        self.label_10.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.lineEdit_parameter_1 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_parameter_1.setGeometry(QtCore.QRect(160, 80, 239, 35))
        self.lineEdit_parameter_1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_1.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_1.setObjectName("lineEdit_parameter_1")
        self.lineEdit_parameter_2 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_parameter_2.setGeometry(QtCore.QRect(160, 160, 239, 35))
        self.lineEdit_parameter_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_2.setObjectName("lineEdit_parameter_2")
        self.lineEdit_parameter_3 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_parameter_3.setGeometry(QtCore.QRect(160, 230, 239, 35))
        self.lineEdit_parameter_3.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_3.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_3.setObjectName("lineEdit_parameter_3")
        self.pushButton_sure_2 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_sure_2.setGeometry(QtCore.QRect(210, 320, 71, 40))
        self.pushButton_sure_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_sure_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_sure_2.setObjectName("pushButton_sure_2")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(70, 370, 431, 31))
        self.label_3.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(30, 30, 91, 91))
        self.label_18.setStyleSheet("border-image: url(:/images/image/GULULU-彩虹宝宝.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_11 = QtWidgets.QLabel(self.page_8)
        self.label_11.setGeometry(QtCore.QRect(210, 20, 301, 41))
        self.label_11.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.lineEdit_parameter_4 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_parameter_4.setGeometry(QtCore.QRect(160, 90, 239, 35))
        self.lineEdit_parameter_4.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_4.setObjectName("lineEdit_parameter_4")
        self.lineEdit_parameter_5 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_parameter_5.setGeometry(QtCore.QRect(160, 160, 239, 35))
        self.lineEdit_parameter_5.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_5.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_5.setObjectName("lineEdit_parameter_5")
        self.lineEdit_parameter_6 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_parameter_6.setGeometry(QtCore.QRect(160, 230, 239, 35))
        self.lineEdit_parameter_6.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_6.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_6.setObjectName("lineEdit_parameter_6")
        self.pushButton_sure_3 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_sure_3.setGeometry(QtCore.QRect(230, 300, 71, 40))
        self.pushButton_sure_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_sure_3.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_sure_3.setObjectName("pushButton_sure_3")
        self.label_8 = QtWidgets.QLabel(self.page_8)
        self.label_8.setGeometry(QtCore.QRect(50, 360, 431, 31))
        self.label_8.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_19 = QtWidgets.QLabel(self.page_8)
        self.label_19.setGeometry(QtCore.QRect(30, 30, 91, 91))
        self.label_19.setStyleSheet("border-image: url(:/images/image/GULULU-彩虹宝宝.png);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        self.label_12.setGeometry(QtCore.QRect(210, 10, 301, 41))
        self.label_12.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit_parameter_7 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_parameter_7.setGeometry(QtCore.QRect(160, 80, 239, 35))
        self.lineEdit_parameter_7.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_7.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_7.setObjectName("lineEdit_parameter_7")
        self.lineEdit_parameter_9 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_parameter_9.setGeometry(QtCore.QRect(160, 240, 239, 35))
        self.lineEdit_parameter_9.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_9.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_9.setObjectName("lineEdit_parameter_9")
        self.lineEdit_parameter_8 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_parameter_8.setGeometry(QtCore.QRect(160, 160, 239, 35))
        self.lineEdit_parameter_8.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_parameter_8.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(0,0,0,100);")
        self.lineEdit_parameter_8.setObjectName("lineEdit_parameter_8")
        self.pushButton_sure_4 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_sure_4.setGeometry(QtCore.QRect(230, 320, 71, 40))
        self.pushButton_sure_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_sure_4.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(40, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_sure_4.setObjectName("pushButton_sure_4")
        self.label_13 = QtWidgets.QLabel(self.page_7)
        self.label_13.setGeometry(QtCore.QRect(70, 370, 431, 31))
        self.label_13.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(36, 108, 0);\n"
"\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.progressBar_3 = QtWidgets.QProgressBar(self.page_7)
        self.progressBar_3.setGeometry(QtCore.QRect(167, 290, 231, 23))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_20 = QtWidgets.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(30, 20, 91, 91))
        self.label_20.setStyleSheet("border-image: url(:/images/image/GULULU-彩虹宝宝.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.stackedWidget_2.addWidget(self.page_7)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_4.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Machine learning"))
        self.pushButton_9.setText(_translate("MainWindow", "主页"))
        self.pushButton_2.setText(_translate("MainWindow", "数据集选择"))
        self.pushButton_5.setText(_translate("MainWindow", "模型算法选择"))
        self.pushButton_6.setText(_translate("MainWindow", "开始实验"))
        self.pushButton_7.setText(_translate("MainWindow", "实验数据"))
        self.pushButton_8.setText(_translate("MainWindow", "我的"))
        self.label_7.setText(_translate("MainWindow", "欢迎使用机器学习系统"))
        self.label_9.setText(_translate("MainWindow", "请选择您的数据集"))
        self.pushButton_select_data.setText(_translate("MainWindow", "选择数据集文件"))
        self.pushButton_select_model_2.setText(_translate("MainWindow", "卷积模型选择"))
        self.pushButton_choose_3.setText(_translate("MainWindow", "测试集选择"))
        self.pushButton_start.setText(_translate("MainWindow", "卷积模型实验"))
        self.label_4.setText(_translate("MainWindow", "            测试集图片"))
        self.label_14.setText(_translate("MainWindow", "              结果"))
        self.pushButton_select_model_3.setText(_translate("MainWindow", "其他模型选择"))
        self.pushButton_start_1.setText(_translate("MainWindow", "其余模型实验"))
        self.label_15.setText(_translate("MainWindow", "请输入您想修改的账号密码与邮箱"))
        self.lineEdit_user_password.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_user_email.setPlaceholderText(_translate("MainWindow", "邮箱："))
        self.pushButton_save_user_info.setText(_translate("MainWindow", "保存"))
        self.lineEdit_user_account_2.setPlaceholderText(_translate("MainWindow", "账号："))
        self.pushButton_model_1.setText(_translate("MainWindow", "支持向量机"))
        self.pushButton_model_2.setText(_translate("MainWindow", "随机森林"))
        self.pushButton_model_3.setText(_translate("MainWindow", "卷积神经网络"))
        self.label_10.setText(_translate("MainWindow", "参数选择"))
        self.lineEdit_parameter_1.setPlaceholderText(_translate("MainWindow", "惩罚系数C："))
        self.lineEdit_parameter_2.setPlaceholderText(_translate("MainWindow", "核函数的参数："))
        self.lineEdit_parameter_3.setPlaceholderText(_translate("MainWindow", "误差权重："))
        self.pushButton_sure_2.setText(_translate("MainWindow", "训练"))
        self.label_11.setText(_translate("MainWindow", "参数选择"))
        self.lineEdit_parameter_4.setPlaceholderText(_translate("MainWindow", "树的数量："))
        self.lineEdit_parameter_5.setPlaceholderText(_translate("MainWindow", "最大特征数："))
        self.lineEdit_parameter_6.setPlaceholderText(_translate("MainWindow", "决策树深度："))
        self.pushButton_sure_3.setText(_translate("MainWindow", "确定"))
        self.label_12.setText(_translate("MainWindow", "参数选择"))
        self.lineEdit_parameter_7.setPlaceholderText(_translate("MainWindow", "卷积核大小："))
        self.lineEdit_parameter_9.setPlaceholderText(_translate("MainWindow", "批量大小："))
        self.lineEdit_parameter_8.setPlaceholderText(_translate("MainWindow", "学习率："))
        self.pushButton_sure_4.setText(_translate("MainWindow", "确定"))
import res_rc
